{
  "name": "MyElectricalData Custom",
  "slug": "myelectricaldata_custom",
  "version": "1.0.0",
  "description": "HAOS addon basé sur MyElectricalData officiel",
  "startup": "services",
  "boot": "auto",
  "arch": ["amd64", "aarch64", "armv7"],
  "host_network": true,
  "options": {},
  "schema": {}
}
